---

- name: Remove unused packages
  apt:
    state: absent
    purge: yes
    name:
      - sympl-ftp
      - sympl-phpmyadmin
      - sympl-mail
      - sympl-webmail
      - pure-ftpd
      - pure-ftpd-common
      - phpmyadmin
      - php-imap
      - sympl-web
      - apache2
      - apache2-bin
      - apache2-data
      - apache2-utils
      - libapache2-mod-php
      - libapache2-mod-vhost-bytemark
      - spamassassin
      - clamav
