- name: Create site user
  user: name=theatricalia uid=1010 shell=/bin/bash

- name: Make sure admin is in the group
  user: name=admin append=yes groups=theatricalia

- name: Create site dir {{ domain }}
  file: path=/srv/{{ domain }} state=directory owner=admin group=theatricalia mode=0775

- name: Create site mailbox dir {{ domain }}
  file: path=/srv/{{ domain }}/mailboxes/principal state=directory owner=admin group=admin

- name: Create site config dir {{ domain }}
  file: path=/srv/{{ domain }}/config state=directory owner=admin group=admin

- name: Create site media dir {{ domain }}
  file: path=/srv/{{ domain }}/media state=directory owner=theatricalia group=theatricalia

- name: Create email forward {{ domain }}
  copy: dest=/srv/{{ domain }}/mailboxes/principal/forward content="{{ email }}" owner=admin group=admin

- name: Create site crontab
  copy: dest=/srv/theatricalia.com/config/crontab content="0 0 * * * /srv/theatricalia.com/theatricalia/bin/flickr-import" owner=admin group=admin

- name: Public files {{ domain }}
  copy: dest=/srv/{{ domain }}/public/htdocs/robots.txt content="" owner=admin group=theatricalia

- name: Symlink media {{ domain }}
  file: path=/srv/{{ domain }}/public/htdocs/media src=/srv/{{ domain }}/media state=link

- name: Symlink static {{ domain }}
  file: path=/srv/{{ domain }}/public/htdocs/static src=/srv/{{ domain }}/collected_static state=link force=yes

- name: Favicon {{ domain }}
  copy: src=favicon.ico dest=/srv/{{ domain }}/public/htdocs/

- name: Add SSH key (public)
  copy: dest=/home/theatricalia/.ssh/id_rsa.pub src=id_rsa.pub owner=theatricalia group=theatricalia

- name: Add SSH key (private)
  copy: dest=/home/theatricalia/.ssh/id_rsa src=id_rsa owner=theatricalia group=theatricalia mode=0600

- name: Fetch site from github {{ domain }}
  become_user: theatricalia
  git: repo=ssh://git@github.com/dracos/Theatricalia.git dest=/srv/{{ domain }}/theatricalia update=no

- name: Add config file {{ domain }}
  template: dest=/srv/{{ domain }}/theatricalia/theatricalia/settings/config.py src=config.py.j2 owner=theatricalia group=theatricalia
  vars:
    db_name: theatricalia{% if domain == 'staging.theatricalia.com' %}_staging{% endif %}

- name: Generate collected static {{ domain }}
  command: /home/theatricalia/.virtualenvs/theatricalia{% if domain == 'staging.theatricalia.com' %}-staging{% endif %}/bin/python manage.py collectstatic --noinput
  become_user: theatricalia
  args:
    chdir: /srv/{{ domain }}/theatricalia
