- name: Install needed packages
  apt: name={{ item }} state=latest
  with_items:
    - libmysqlclient-dev
    - libjpeg-dev
    - python-dev
    - python-mysqldb
    - virtualenv

- name: Set up virtualenv
  pip: virtualenv=/home/theatricalia/.virtualenvs/theatricalia name="{{ item }}"
  with_items:
    - Django==1.8.17
    - MySQL-python==1.2.5
    - Pillow==3.1.1
    - django-reversion==1.10.2
    - django-contrib-comments==1.7.3
    - sorl-thumbnail==12.3
    - django-nose==1.4.4
    - python-dateutil==2.4.2
    - six==1.10.0
    - gunicorn==19.0.0

- name: Set up virtualenv (staging)
  pip: virtualenv=/home/theatricalia/.virtualenvs/theatricalia-staging name="{{ item }}"
  with_items:
    - Django==1.8.17
    - MySQL-python==1.2.5
    - Pillow==3.1.1
    - django-reversion==1.10.2
    - django-contrib-comments==1.7.3
    - sorl-thumbnail==12.3
    - django-nose==1.4.4
    - python-dateutil==2.4.2
    - six==1.10.0
    - gunicorn==19.0.0
