---
- name: Set up server
  hosts: all
  pre_tasks:
    - name: Update APT
      apt: update_cache=yes
    - name: Install the necessities
      apt: name={{ item }} state=latest
      with_items:
        - git
        - strace
        - vim
        - jq
        - mutt
        - php-curl
  roles:
  - symbiosis-tidy
  - backup
  - nginx
  - gunicorn
  - theatricalia
  - postboxes
  - labs
