---
- name: Set up server
  hosts: all
  pre_tasks:
    - name: Update APT
      apt: update_cache=yes
    - name: Install the necessities
      apt:
        state: latest
        name:
          - git
          - strace
          - vim
          - jq
          - mutt
          - php-curl
  roles:
  - symbiosis-tidy
  - backup
  - nginx
  - uwsgi
  - theatricalia
  - postboxes
  - pepysshows
  - bots
  - labs
