- name: Install needed packages
  apt:
    state: latest
    name:
      - libmysqlclient-dev
      - libjpeg-dev
      - python3-dev
      - python3-mysqldb
      - python-setuptools
      - virtualenv

- name: Set up virtualenv
  pip:
    virtualenv: /home/theatricalia/.virtualenvs/theatricalia-3
    virtualenv_python: python3
    name:
      - Django==2.2.17
      - mysqlclient==2.0.2
      - Pillow==8.1.2
      - django-reversion==3.0.7
      - django-contrib-comments==2.0.0
      - sorl-thumbnail==12.7.0
      - django-nose==1.4.7
      - python-dateutil==2.8.1
      - six==1.15.0

- name: Set up virtualenv (staging)
  pip:
    virtualenv: /home/theatricalia/.virtualenvs/theatricalia-3-staging
    virtualenv_python: python3
    name:
      - Django==2.2.17
      - mysqlclient==2.0.2
      - Pillow==8.1.2
      - django-reversion==3.0.7
      - django-contrib-comments==2.0.0
      - sorl-thumbnail==12.7.0
      - django-nose==1.4.7
      - python-dateutil==2.8.1
      - six==1.15.0
      - django-debug-toolbar==2.2
