- name: Set up nginx
  template: src=roles/nginx/templates/site.j2 dest=/etc/nginx/sites-enabled/theatricalia
  vars:
    domain: theatricalia.com
    site: theatricalia
    ssl: 1
  notify:
    - reload nginx

- name: Set up nginx (staging)
  template: src=roles/nginx/templates/site.j2 dest=/etc/nginx/sites-enabled/theatricalia-staging
  vars:
    domain: staging.theatricalia.com
    site: theatricalia-staging
    ssl: 1
  notify:
    - reload nginx

- name: Set up uwsgi
  template: src=roles/uwsgi/templates/uwsgi.j2 dest=/etc/uwsgi/apps-enabled/theatricalia.ini
  vars:
    dir: /srv/theatricalia.com/theatricalia
    user: theatricalia
    group: theatricalia
    site: theatricalia
    wsgi: theatricalia.wsgi
  notify:
    - reload uwsgi

- name: Set up uwsgi (staging)
  template: src=roles/uwsgi/templates/uwsgi.j2 dest=/etc/uwsgi/apps-enabled/theatricalia-staging.ini
  vars:
    dir: /srv/staging.theatricalia.com/theatricalia
    user: theatricalia
    group: theatricalia
    site: theatricalia-staging
    wsgi: theatricalia.wsgi
    num_procs: 2
  notify:
    - reload uwsgi
