- name: Install needed packages
  apt:
    state: latest
    name:
      - php-mysql

- name: Add database
  mysql_db: name=postboxes state=present login_password={{ mysql_password }}

- name: Add database user
  mysql_user: name=postboxes priv=postboxes.*:ALL login_password={{ mysql_password }}

- block:
    - name: Copy schema to tmp
      copy: src=schema.sql dest=/tmp
    - name: Add db tables from tmp
      mysql_db: name=postboxes login_user=postboxes state=import target=/tmp/schema.sql

- include: files.yml
  vars:
    domain: postboxes.dracos.co.uk

- name: Set up nginx
  template: src=roles/nginx/templates/site.j2 dest=/etc/nginx/sites-enabled/postboxes
  vars:
    domain: postboxes.dracos.co.uk
    php: 1
    ssl: 1
    log_type: 'with_time_no_params'
  notify:
    - reload nginx
