- name: Create site dir {{ domain }}
  file: path=/srv/{{ domain }} state=directory owner=admin group=theatricalia mode=0775

- name: Create site config dir {{ domain }}
  file: path=/srv/{{ domain }}/config state=directory owner=admin group=admin

- name: Create site public dir {{ domain }}
  file: path=/srv/{{ domain }}/public/htdocs state=directory owner=admin group=theatricalia

- name: Public files {{ domain }}
  copy: dest=/srv/{{ domain }}/public/htdocs/robots.txt content="" owner=admin group=theatricalia force=no

- name: Set up nginx for {{ domain }}
  template: src=roles/nginx/templates/site.j2 dest=/etc/nginx/sites-enabled/{{ domain }}
  notify:
    - reload nginx
